from app.schemas.enums import Decision, IncidentStage, Severity, DataProvenance
from app.schemas.responses import RansomwareResponse


def get_normal_response() -> RansomwareResponse:
    return RansomwareResponse(
        use_case="ransomware_resilience",
        industry="energy",
        site_id="synthetic-site-001",
        site_type="control_centre",
        scenario_id="rw-stage0-normal",
        decision=Decision.NORMAL,
        incident_stage=IncidentStage.NONE,
        confidence=0.90,
        severity=Severity.LOW,
        resilience_score=85.0,
        affected_assets=[],
        suspected_assets=[],
        potentially_exposed_assets=[],
        protected_assets=[],
        unknown_assets=[],
        critical_services_at_risk=[],
        affected_zones=[],
        protected_boundaries=[],
        operational_dependency_impact=[],
        propagation_path=[],
        evidence_layers=[],
        triggered_rules=[],
        timeline=[],
        backup_readiness={},
        explanations=["No material ransomware progression evidence identified."],
        recommended_actions=["Continue monitoring."],
        human_approval_required=True,
        real_action_executed=False,
        artifact_provenance=[],
        data_provenance=DataProvenance.SYNTHETIC_GROUND_TRUTH,
        warnings=[],
        request_id="stage0-normal-001",
        trace_id="stage0-normal-trace-001",
        runtime_state="mocked",
    )


def get_investigate_response() -> RansomwareResponse:
    return RansomwareResponse(
        use_case="ransomware_resilience",
        industry="energy",
        site_id="synthetic-site-001",
        site_type="control_centre",
        scenario_id="rw-stage0-investigate",
        decision=Decision.INVESTIGATE,
        incident_stage=IncidentStage.PRECURSOR,
        confidence=0.65,
        severity=Severity.MEDIUM,
        resilience_score=65.0,
        affected_assets=[],
        suspected_assets=["synthetic-endpoint-001"],
        potentially_exposed_assets=[],
        protected_assets=[],
        unknown_assets=[],
        critical_services_at_risk=[],
        affected_zones=[],
        protected_boundaries=[],
        operational_dependency_impact=[],
        propagation_path=[],
        evidence_layers=[],
        triggered_rules=[],
        timeline=[],
        backup_readiness={},
        explanations=["Evidence is ambiguous and requires investigation."],
        recommended_actions=["Review the available evidence and investigate the suspected asset."],
        human_approval_required=True,
        real_action_executed=False,
        artifact_provenance=[],
        data_provenance=DataProvenance.SYNTHETIC_GROUND_TRUTH,
        warnings=[],
        request_id="stage0-investigate-001",
        trace_id="stage0-investigate-trace-001",
        runtime_state="mocked",
    )


def get_high_risk_response() -> RansomwareResponse:
    return RansomwareResponse(
        use_case="ransomware_resilience",
        industry="petrochemical",
        site_id="synthetic-site-001",
        site_type="refinery",
        scenario_id="rw-stage0-high-risk",
        decision=Decision.HIGH_RISK,
        incident_stage=IncidentStage.LATERAL_MOVEMENT,
        confidence=0.88,
        severity=Severity.HIGH,
        resilience_score=40.0,
        affected_assets=["synthetic-host-001"],
        suspected_assets=["synthetic-host-002"],
        potentially_exposed_assets=[],
        protected_assets=[],
        unknown_assets=[],
        critical_services_at_risk=[],
        affected_zones=[],
        protected_boundaries=[],
        operational_dependency_impact=[],
        propagation_path=[],
        evidence_layers=[],
        triggered_rules=[],
        timeline=[],
        backup_readiness={},
        explanations=["Synthetic evidence indicates elevated ransomware risk."],
        recommended_actions=["Escalate for human review and assess recommended containment actions."],
        human_approval_required=True,
        real_action_executed=False,
        artifact_provenance=[],
        data_provenance=DataProvenance.SYNTHETIC_GROUND_TRUTH,
        warnings=[],
        request_id="stage0-high-risk-001",
        trace_id="stage0-high-risk-trace-001",
        runtime_state="mocked",
    )


def get_unavailable_response() -> RansomwareResponse:
    return RansomwareResponse(
        use_case="ransomware_resilience",
        industry="energy",
        site_id="synthetic-site-001",
        site_type="control_centre",
        scenario_id="rw-stage0-unavailable",
        decision=Decision.UNAVAILABLE,
        incident_stage=IncidentStage.NONE,
        confidence=0.0,
        severity=Severity.CRITICAL,
        resilience_score=0.0,
        affected_assets=[],
        suspected_assets=[],
        potentially_exposed_assets=[],
        protected_assets=[],
        unknown_assets=[],
        critical_services_at_risk=[],
        affected_zones=[],
        protected_boundaries=[],
        operational_dependency_impact=[],
        propagation_path=[],
        evidence_layers=[],
        triggered_rules=[],
        timeline=[],
        backup_readiness={},
        explanations=[],
        recommended_actions=[],
        human_approval_required=True,
        real_action_executed=False,
        artifact_provenance=[],
        data_provenance=DataProvenance.UNAVAILABLE,
        warnings=["Synthetic runtime failure: response unavailable."],
        request_id="stage0-unavailable-001",
        trace_id="stage0-unavailable-trace-001",
        runtime_state="unavailable",
    )


def get_fallback_response() -> RansomwareResponse:
    return RansomwareResponse(
        use_case="ransomware_resilience",
        industry="energy",
        site_id="synthetic-site-001",
        site_type="control_centre",
        scenario_id="rw-stage0-fallback",
        decision=Decision.INVESTIGATE,
        incident_stage=IncidentStage.PRECURSOR,
        confidence=0.50,
        severity=Severity.MEDIUM,
        resilience_score=60.0,
        affected_assets=[],
        suspected_assets=[],
        potentially_exposed_assets=[],
        protected_assets=[],
        unknown_assets=[],
        critical_services_at_risk=[],
        affected_zones=[],
        protected_boundaries=[],
        operational_dependency_impact=[],
        propagation_path=[],
        evidence_layers=[],
        triggered_rules=[],
        timeline=[],
        backup_readiness={},
        explanations=["Fallback synthetic response; this is not live-model output."],
        recommended_actions=["Review the fallback result and investigate available evidence."],
        human_approval_required=True,
        real_action_executed=False,
        artifact_provenance=[],
        data_provenance=DataProvenance.FALLBACK,
        warnings=["FALLBACK: live-model output is unavailable."],
        request_id="stage0-fallback-001",
        trace_id="stage0-fallback-trace-001",
        runtime_state="fallback",
    )
